version: '3.4'

services:
  grand.web:
    image: gabrielfreiredev/pyramidshop:latest
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: Dockerfile
