version: '3.4'

services:
  pyramidshop:
    image: gabrielfreiredev/pyramidshop:latest
    ports:
      - 5100:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: Dockerfile